prique:main.o PriorityQueue.o
	g++ -o prique main.o PriorityQueue.o
main.o:main.cpp PriorityQueue.cpp
	g++ -c -o main.o main.cpp
PriorityQueue.o:PriorityQueue.cpp
	g++ -c -o PriorityQueue.o PriorityQueue.cpp